### ISSUE TITLE
Unknown connection protocol cifs

### ISSUE THREAD

**Issue by SergeyFedechkin** [xebialabs/overthere#107]
Hello.

I use Overthere 2.3.1. With local machine client works perfectly. But when I try to call same code included to EJB, I`ve got error "Unknown connection protocol cifs" in method Overthere.getConnection.

I`ve looked over the source and found that the class contains Protocol annotation scanner with hardcoded class name:

Scannit scannit = new Scannit(Configuration.config().scan("com.xebialabs").with(new AbstractScanner[] { new TypeAnnotationScanner() }));

Seems like annotation scanner returns null result in case of EJB.

Could anyone help me, what the class name should be used in scanner? Is it any feature to make Overthere working in EJB context?

Best regards,
Sergey.

**Comment by mayurbavisiya** [comment]
Hello.

I have tried Overthere 2.3.1 to 5.0.3. With local machine on tomcat server works perfectly. But when I try to call same code on test env included to weblogic, I`ve got error "Unknown connection protocol cifs" in method Overthere.getConnection.

for (<URL> e = Thread.currentThread().getContextClassLoader().getResources("com/xebialabs");
        e.hasMoreElements();) {
    System.out.println(e.nextElement());
}

i am getting correct path from weblogic directory. But still not working :(
Any one can help on this.

**Comment by hierynomus** [comment]
Try to use the new OverthereConnector to manually register the protocol classes. This circumvents the classloader issues in some containers

**Comment by mayurbavisiya** [comment]
hi @hierynomus 

Still getting same , Now i am using OverthereConnector and exception is same.



stacktrace":"java.lang.IllegalArgumentException: Unknown connection protocol cifs\n\tat ae.dubaipolice.powershell.OverthereConnector.getConnection(OverthereConnector.java:52)\n\tat ae.dubaipolice.powershell.CustomOverthere.getConnection(CustomOverthere.java:65)\n\tat ae.dubaipolice.powershell.PowerShellScriptServiceImpl.executePowerShellScript(PowerShellScriptServiceImpl.java:110)\n\tat ae.dubaipolice.powershell.PowerShellScriptServiceImpl.setPowerShellActionInputs(PowerShellScriptServiceImpl.java:85)\n\tat ae.dubaipolice.SearchUserLdap.SearchUserLdapServiceImpl.updateMailBox(SearchUserLdapServiceImpl.java:451)\n\tat ae.dubaipolice.SearchUserLdap.SearchUserLdapServiceImpl$$FastClassBySpringCGLIB$$7cf96088.invoke(<generated>)\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\n\tat org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)\n\tat ae.dubaipolice.SearchUserLdap.SearchUserLdapServiceImpl$$EnhancerBySpringCGLIB$$85d10e45.updateMailBox(<generated>)\n\tat ae.dubaipolice.SearchUserLdap.SearchUserLdapAction.updateMailBox(SearchUserLdapAction.java:382)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:894)\n\tat ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1539)\n\tat ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)\n\tat com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:96)\n\tat com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:88)\n\tat ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1615)\n\tat ognl.ASTMethod.getValueBody(ASTMethod.java:91)\n\tat ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)\n\tat ognl.SimpleNode.getValue(SimpleNode.java:258)\n\tat ognl.Ognl.getValue(Ognl.java:467)\n\tat ognl.Ognl.getValue(Ognl.java:431)\n\tat com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:351)\n\tat com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:403)\n\tat com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:349)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:436)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:291)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:252)\n\tat org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:253)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:177)\n\tat com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:260)\n\tat org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:73)\n\tat com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:139)\n\tat com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:133)\n\tat com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:133)\n\tat com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:192)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:69)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:115)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:88)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:324)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:99)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:139)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:155)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:174)\n\tat com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:120)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:171)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:195)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:193)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat ae.dubaipolice.Utils.XSSInterceptor.intercept(XSSInterceptor.java:41)\n\tat com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)\n\tat org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:54)\n\tat org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564)\n\tat org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:81)\n\tat org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:143)\n\tat weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)\n\tat ae.dubaipolice.identityserver.filter.IdentityFilter.doFilter(IdentityFilter.java:156)\n\tat weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)\n\tat oracle.security.jps.ee.http.JpsFilter.doFilter(JpsFilter.java:92)\n\tat weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)\n\tat oracle.dms.servlet.DMSServletFilter.doFilter(DMSServletFilter.java:224)\n\tat weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)\n\tat weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3654)\n\tat weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3620)\n\tat weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)\n\tat weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:196)\n\tat weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)\n\tat weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)\n\tat weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2423)\n\tat weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2280)\n\tat weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2258)\n\tat weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1626)\n\tat weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1586)\n\tat weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:270)\n\tat weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:348)\n\tat weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:333)\n\tat weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:54)\n\tat weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)\n\tat weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:617)\n\tat weblogic.work.ExecuteThread.execute(ExecuteThread.java:397)\n\tat weblogic.work.ExecuteThread.run(ExecuteThread.java:346)","exception_class":"java.lang.IllegalArgumentException","exception_message":"Unknown connection protocol cifs"

**Comment by mayurbavisiya** [comment]
Now i am getting 

java.lang.IllegalStateException: Cannot instantiate class com.xebialabs.overthere.cifs.CifsConnectionBuilder


I am calling registerprotocol method like as follow

 public static OverthereConnection getConnection(String protocol, final ConnectionOptions options) {
    	logger.info("calling register protocol");
    	connector.registerProtocol(com.xebialabs.overthere.proxy.ProxyConnection.class);
    	connector.registerProtocol(com.xebialabs.overthere.ssh.SshConnectionBuilder.class);
    	connector.registerProtocol(com.xebialabs.overthere.smb.SmbConnectionBuilder.class);
    	connector.registerProtocol(com.xebialabs.overthere.cifs.CifsConnectionBuilder.class);
    	connector.registerProtocol(com.xebialabs.overthere.ssh.SshJumpstationConnectionBuilder.class);
    	connector.registerProtocol(com.xebialabs.overthere.local.LocalConnection.class);    	
        return connector.getConnection(protocol, options);
    }

is it right way to call ?

**Comment by mayurbavisiya** [comment]
@hierynomus us Thanks , Its working now for me, But now i am stick in OS level issue.

Code is running perfectly in tomcat and web logic but only in window. When i deployed code in testing web logic which installed in Oracle Linux its giving exception
Cannot create a " + SMB_PROTOCOL + ":%s connection with a winrs proxy that is not running Windows"

Please suggest on this.

**Comment by hierynomus** [comment]
@mayurbavisiya This is described in the README I think. `winrs` (`WINRM_NATIVE`) is only supported on a Windows machine. For a Linux machine you need to use `WINRM_INTERNAL`.
