### ISSUE TITLE
Add support for reverse ssh tunneling

### ISSUE THREAD

**Issue by mingfang** [xebialabs/overthere#119]
Currently SshTunnelConnection only supports local port forwarding.  Please add support for reverse port forwarding.

**Comment by hierynomus** [comment]
@mingfang Can you give us a usecase, so that we can take it into consideration. Also what/how would be the best way to configure this.

**Comment by hierynomus** [comment]
Also this only makes sense for SSH, not for any of the other abstractions that Overthere offers. You might be better off using SSHJ directly, which actually supports this.

**Comment by mingfang** [comment]
Thanks for looking into this.
I'll withdraw this request since I no longer need it.
