### ISSUE TITLE
WinRmRuntimeIOException - Unexpected HTTP response 

### ISSUE THREAD

**Issue by adinatusa** [xebialabs/overthere#135]
Hello,

I want to run from a Java Client the following command on a remote Windows the following line and grab the result:
winrm enumerate wmicimv2/* -filter:"select Name,Version from Win32_OperatingSystem" -r:http://<Host>:5985 -u:administrator -p:<Pass>

From the client machine a successfully run this command and all the setup from run remote a winrm command was done.

I downloaded the examples from overtere-master and I tried to run ExecuteOnWindows.java:
ConnectionOptions options = new ConnectionOptions();
        options.set(ADDRESS, "Host");
        options.set(USERNAME, "MyUser");
        options.set(PASSWORD, "MyPass");
        options.set(OPERATING_SYSTEM, WINDOWS);
        options.set(CONNECTION_TYPE, WINRM_INTERNAL);
        OverthereConnection connection = Overthere.getConnection("cifs", options);
....
     connection.execute(CmdLine.build("type", "\\windows\\system32\\drivers\\etc\\hosts"));

I got the following exception:
Exception in thread "main" com.xebialabs.overthere.cifs.winrm.WinRmRuntimeIOException: Unexpected HTTP response on http://<Host>:5985/wsman:   (401)

How can I use overthere library?

Thank you.

**Comment by vpartington** [comment]
Closed due to lack of activity.
