### ISSUE TITLE
Unknow connection protocol

### ISSUE THREAD

**Issue by eblikstad** [xebialabs/overthere#163]
I'm getting the error message "Unknown connection protocol local" in Rundeck.

The boot(Scannit scannit) function in the class Overthere does not seem to work under some circumstances. I'm using the Rundeck tool and it uses a plugin called rundeck-winrm-plugin which uses  Overthere. This causes the verification in the getConnection function to fail.

The woraround was to enter the protocols manually in the boot function.
Overthere.protocols.get().put("cifs", (Class<? extends OverthereConnectionBuilder>) CifsConnectionBuilder.class);
Overthere.protocols.get().put("local", (Class<? extends OverthereConnectionBuilder>) LocalConnection.class);
Overthere.protocols.get().put("ssh", (Class<? extends OverthereConnectionBuilder>) SshConnectionBuilder.class);                        

There seems to be a problem with the scannit-1.3.1.jar library which may not work running in the Jetty environment which Rundeck use. The problem does noe occur with a plain sample Java project I made during troubleshooting this issue.

**Comment by gschueler** [comment]
@eblikstad can you do the manual setup within the rundeck-winrm-plugin to workaround the issue for that case?

**Comment by eblikstad** [comment]
I will look into that. I'm hoping this does not require too much coding.

**Comment by hierynomus** [comment]
Are you running the rundeck plugin under Java8?

**Comment by desaim** [comment]
I ran into the same issue as eblikstad.  I am testing on a Windows with Java version 1.8.0_65.

**Comment by vpartington** [comment]
Closed due to lack of activity.
