### ISSUE TITLE
Unknown connection protocol cifs 

### ISSUE THREAD

**Issue by folly3** [xebialabs/overthere#175]
hello,

i have a problem with my app in production environment, " java.lang.IllegalArgumentException: Unknown connection protocol cifs ".

But in local environment on tomcat my app run fine.

@SergeyFedechkin 
you can say me how you resolve your issue.
https://github.com/xebialabs/overthere/issues/107

best regards.

Folly

**Comment by SergeyFedechkin** [comment]
Hello. This error relates to app classloader issue. First and right way is to build your app including all libs in proper sequence (check links on github project info). Other way is to try to add overthere lib to classloader hierarchy programatically on runtime.

**Comment by folly3** [comment]
Hello SergeyFedechkin,

Thank you for your response, but you can give me links for including libs in proper sequence.
I found nothing, i am a bad searcher.

Thanks again.

Folly
