### ISSUE TITLE
JBoss EAP 6.4 and Overthere (Unknown connection protocol ssh)

### ISSUE THREAD

**Issue by Thuetar** [xebialabs/overthere#179]
I'm struggling to get this to work inside Jboss.
my junit tests pass, but the same code fails inside JBoss. Hope someone out there has seen this before, as I'd love to get this working.

11:23:01,097 INFO  [com.x.x.x.x.v1.engine.Linux](http-/0.0.0.0:8080-1) Entered : Execute Remote Command
11:23:01,097 DEBUG [nl.javadude.scannit.reader.ClasspathReader](http-/0.0.0.0:8080-1) Finding resources for prefix: com/xebialabs
11:23:01,097 DEBUG [nl.javadude.scannit.reader.ClasspathReader](http-/0.0.0.0:8080-1) Encountered URL: vfs:/c:/java/JBoss64/jboss-eap-6.4/standalone/deployments/dataops-war.war/WEB-INF/lib/overthere-4.3.2.jar/com/xebialabs/
11:23:01,097 DEBUG [nl.javadude.scannit.reader.ClasspathReader](http-/0.0.0.0:8080-1) Found base uris: [vfs:/c:/java/JBoss64/jboss-eap-6.4/standalone/deployments/dataops-war.war/WEB-INF/lib/overthere-4.3.2.jar/c]
11:23:01,107 CONFIG [de.schlichtherle.truezip.util.ServiceLocator](http-/0.0.0.0:8080-1) 

---

*\*                              TrueZIP 7.7.8                             **
*\*           Copyright (C) 2005-2015 Schlichtherle IT Services            **
*\*         All rights reserved. Use is subject to license terms.          **
*\* ---------------------------------------------------------------------- **
*\* If TrueZIP has helped you or your organization to save some valuable   **
*\* development time or enable new features in your application, then      **
*\* please consider making a donation. Any donation contributes to the     **
*\* ongoing development and support of the TrueZIP project.                **
*\* For more information please visit http://truezip.java.net .            **

---

11:23:01,117 CONFIG [de.schlichtherle.truezip.fs.sl.FsManagerLocator](http-/0.0.0.0:8080-1) Using de.schlichtherle.truezip.fs.sl.FsManagerLocator$DefaultManagerService[priority=0].
11:23:01,117 CONFIG [de.schlichtherle.truezip.fs.sl.FsManagerLocator](http-/0.0.0.0:8080-1) Result is de.schlichtherle.truezip.fs.FsDefaultManager[size=0].
11:23:01,127 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Located de.schlichtherle.truezip.fs.file.FileDriverService.
11:23:01,127 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Located de.schlichtherle.truezip.fs.nio.file.FileDriverService.
11:23:01,147 CONFIG [de.schlichtherle.truezip.socket.sl.IOPoolLocator](http-/0.0.0.0:8080-1) Located de.schlichtherle.truezip.fs.file.TempFilePoolService[priority=0].
11:23:01,147 CONFIG [de.schlichtherle.truezip.socket.sl.IOPoolLocator](http-/0.0.0.0:8080-1) Located de.schlichtherle.truezip.fs.nio.file.TempFilePoolService[priority=100].
11:23:01,147 CONFIG [de.schlichtherle.truezip.socket.sl.IOPoolLocator](http-/0.0.0.0:8080-1) Using de.schlichtherle.truezip.fs.nio.file.TempFilePoolService[priority=100].
11:23:01,147 CONFIG [de.schlichtherle.truezip.socket.sl.IOPoolLocator](http-/0.0.0.0:8080-1) Result is de.schlichtherle.truezip.fs.nio.file.TempFilePool@72d26d96.
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Located de.schlichtherle.truezip.fs.archive.zip.ZipDriverService.
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme ear to file system driver de.schlichtherle.truezip.fs.archive.zip.JarDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme exe to file system driver de.schlichtherle.truezip.fs.archive.zip.ReadOnlySfxDriver[charset=windows-1252, federated=true, priority=0].
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme file to file system driver de.schlichtherle.truezip.fs.nio.file.FileDriver[federated=false, priority=100].
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme jar to file system driver de.schlichtherle.truezip.fs.archive.zip.JarDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odb to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odc to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,147 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odf to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odg to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odi to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odm to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odp to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme ods to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme odt to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme otc to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme otf to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme otg to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme oth to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme oti to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme otp to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme ots to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme ott to file system driver de.schlichtherle.truezip.fs.archive.zip.OdfDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme war to file system driver de.schlichtherle.truezip.fs.archive.zip.JarDriver[charset=UTF-8, federated=true, priority=0].
11:23:01,157 CONFIG [de.schlichtherle.truezip.fs.sl.FsDriverLocator](http-/0.0.0.0:8080-1) Mapping scheme zip to file system driver de.schlichtherle.truezip.fs.archive.zip.ZipDriver[charset=IBM437, federated=true, priority=0].
11:23:01,257 ERROR [com.x.x.x.x.v1.rest.EngineRESTService](http-/0.0.0.0:8080-1) Unknown connection protocol ssh
11:23:01,257 ERROR [com.x.x.x.x.v1.rest.EngineRESTService](http-/0.0.0.0:8080-1) java.lang.IllegalArgumentException: Unknown connection protocol ssh

**Comment by hierynomus** [comment]
This is related to hierynomus/scannit#11. Which is fixed in scannit v1.4.1
