### ISSUE TITLE
Failed to obtain huawei switch configuration file using SFTP protocol

### ISSUE THREAD

**Issue by 16207769** [xebialabs/overthere#226]
I want to connect to the switch through the SFTP protocol and get the files on the switch. How can this function be realized

**Comment by vpartington** [comment]
Hi,

The documentation for Overthere can be found in the README.md file:
https://github.com/xebialabs/overthere/blob/master/README.md

If you have specific problem, please describe what you're doing, what you're expecting to happen and what actually happened.

Regards, Vincent.
