### ISSUE TITLE
MaxMemoryPerShellMB quota ignored by WinRM 3.0

### ISSUE THREAD

**Issue by zerikv** [xebialabs/overthere#64]
Hello,

Ok I know, is not really an issue which concern directly `Overthere` but `WinRM`, hence I apologize in advance if you see this post as a pollution.

I'm a bit desperate and I'm looking for people concerned by WinRM.

My problem is the following: 
since I have installed WinRM 3.0 (which is included in WFM 3.0 provided by KB2506143), the quota "MaxMemoryPerShellMB" seems no longer used.

I have set this quota to the 2 Gb value:

```
C:\WINDOWS\system32>winrm get winrm/config/winrs
Winrs
    MaxMemoryPerShellMB = 2048
```

But when I launch a JVM via the Remote Shell I can't allocate more than 114 Mb for the heap:

```
C:\WINDOWS\system32>winrs -r:localhost -unencrypted -u:.\carladmin -p:xxxxxxx java -Xms114m -version
java version "1.6.0_25"
Java(TM) SE Runtime Environment (build 1.6.0_25-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.0-b11, mixed mode)
```

```
C:\WINDOWS\system32>winrs -r:localhost -unencrypted -u:.\carladmin -p:xxxxxxx java -Xms115m -version
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 384 bytes for CHeapObj-new
# An error report file with more information is saved as:
# C:\Users\carladmin.EVE-SEVEN\hs_err_pid6308.log
```

This issue occurs only with WinRM 3.0 (if I uninstall the update "KB2506143" and go back with WinRM 2.0 all works fine and I can allocate heap with 256 Mb and more).

Did you meet a similar issue?

Do you know a workaround?

Thank you for your opinion about this issue.

**Comment by charanteja333** [comment]
Hello,

I am still facing the issue after applying the hotfix in Windows server 2008 R2 SP1.
"Error occurred during initialisation of VM. Could not reserve enough space for object heap"

This error occurs when i run a java application from powershell window remotely. I have changed the maxmemorypershellMB parameter but still it doesn't work.

Regards,
Charan

**Comment by hierynomus** [comment]
Hi Charan,

What is the error you're getting? Are you also setting the correct -Xmx and -Xms settings for the java process?

**Comment by charanteja333** [comment]
Hi ,

Yes i have the set the -Xmx and -Xms in the environment variables 
-Xms2048m -Xmx4096m -XX:PermSize=256M -XX:MaxPermSize=512M.
I get the error 
**Error occurred during initialization of VM
Could not reserve enough space for object heap**

Regards,
Charan

**Comment by hierynomus** [comment]
That means that your WinRM MaxMemoryPerShell is not set high enough to accommodate the minimum memory the Java process needs.
