### ISSUE TITLE
Add support for KDC behind SSH jumpstation

### ISSUE THREAD

**Issue by vpartington** [xebialabs/overthere#74]
Add support for CIFS/WinRM connections tunneled over SSH using Windows domain accounts with the KDC (= Windows domain controller) also behind the jumpstation.

1. Document how to set up the `krb5.conf`.
2. Add support for static SSH tunnels. When the first CIFS/WinRM connection that needs it is opened, the tunnel is opened. When the last one is closed, the tunnel is closed too.

**Comment by vpartington** [comment]
Closed due to lack of interest.

**Comment by aadrianson** [comment]
We've had a few users interested in this in the last year.  Interest seems likely to increase. Please consider re-opening.
