### ISSUE TITLE
401 kerberos authentication problem

### ISSUE THREAD

**Issue by SergeyFedechkin** [xebialabs/overthere#94]
Hello.

I try to implement the domain account authentication with Kerberos from non-domain workstation. I`ve gone through all required steps for source and remote hosts.

With WINRM_KERBEROS_DEBUG option I see that client sends request to domain controller, gets TGT:

Debug is  true storeKey false useTicketCache false useKeyTab false doNotPrompt false ticketCache is null isInitiator true KeyTab is null refreshKrb5Config is true principal is null tryFirstPass is false useFirstPass is false storePass is false clearPass is false
Refreshing Kerberos configuration
		[Krb5LoginModule] user entered username: Test@CONTOSO

Acquire TGT using AS Exchange
principal is Test@CONTOSO
EncryptionKey:
       (EncryptionKey data)
Commit Succeeded 

The SPN contains records:

WSMAN/TEST-SERVER
WSMAN/TEST-SERVER.contoso

WinRM service config:

Service
    RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)S:P(AU;FA;GA;;;WD)(AU;SA;GWGX;;;WD)
    MaxConcurrentOperations = 4294967295
    MaxConcurrentOperationsPerUser = 1500
    EnumerationTimeoutms = 240000
    MaxConnections = 300
    MaxPacketRetrievalTimeSeconds = 120
    AllowUnencrypted = true
    Auth
        Basic = true
        Kerberos = true
        Negotiate = true
        Certificate = false
        CredSSP = false
        CbtHardeningLevel = Relaxed
    DefaultPorts
        HTTP = 5985
        HTTPS = 5986
    IPv4Filter = *
    IPv6Filter = *
    EnableCompatibilityHttpListener = false
    EnableCompatibilityHttpsListener = false
    CertificateThumbprint
    AllowRemoteAccess = true
Winrs
    AllowRemoteShellAccess = true
    IdleTimeout = 7200000
    MaxConcurrentUsers = 10
    MaxShellRunTime = 2147483647
    MaxProcessesPerShell = 25
    MaxMemoryPerShellMB = 1024
    MaxShellsPerUser = 30

But HTTP-request contains only Basic authorization header:

POST /wsman HTTP/1.1
Content-Length: 1604
Content-Type: application/soap+xml; charset=UTF-8
Host: TEST-SERVER.contoso:5985
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.2.1 (java 1.5)
Authorization: Basic VGVzdEBDT05UT1NPOnRlc3RwYXNz

After that I`ve got HTTP response status 401:

HTTP/1.1 401 
Server: Microsoft-HTTPAPI/2.0
WWW-Authenticate: Negotiate
WWW-Authenticate: Kerberos
WWW-Authenticate: Basic realm="WSMAN"
Date: Fri, 24 Jan 2014 11:47:50 GMT
Connection: close
Content-Length: 0

The windows server event:
User authentication using Basic authentication scheme failed. 

What`s wrong or missing with kerberos config?

Best regards,
Sergey.

**Comment by jp** [comment]
I've had the exact same issue (plugin using Basic auth instead of Kerberos ticket).

I also had the following log:

```
WARN  RequestTargetAuthentication: NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7)))
```

I was able to fix this by stopping to use the IP of the machine, and replacing it by the name of the machine.

It might help ...
