### ISSUE TITLE
Some special characters disturb the command line on Linux.

### ISSUE THREAD

**Issue by zerikv** [xebialabs/overthere#99]
Hello,

I have problems with arguments of command line on Linux when they contain special characters like: ! < >

When the bash expands the command line, < and > are interpreted as stream redirectors and ! as selector in the history.

To solve this issue I have added these characters in the constant com.xebialabs.overthere.CmdLineArgument.SPECIAL_CHARS_UNIX

Eric

**Comment by Naba0106** [comment]
What if we actually want to use stream redirects?

**Comment by Naba0106** [comment]
Got it, have to use addRaw(">"):
```javascript
CmdLine.build("echo", "-e", "test").addRaw(">").addRaw("test.txt")
```
